# Generated by Django 4.2.1 on 2023-10-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_talkroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkroom',
            name='message',
            field=models.CharField(verbose_name='message'),
        ),
    ]
